Fix complie error on macOS 10.14.2 AppleClang 10.0.0.10001145
[ 60%] Building CXX object doc/examples/spdlog/CMakeFiles/vuh_example_spdlog.dir/main.cpp.o
/Users/longsky/Source/vuh/doc/examples/spdlog/main.cpp:13:27: error: no member
      named 'basic_logger_mt' in namespace 'spdlog'
static auto logger = spd::basic_logger_mt("logger", "vuh.log");
                     ~~~~~^
1 error generated.
make[2]: *** [doc/examples/spdlog/CMakeFiles/vuh_example_spdlog.dir/main.cpp.o] Error 1
make[1]: *** [doc/examples/spdlog/CMakeFiles/vuh_example_spdlog.dir/all] Error 2
make: *** [all] Error 2

spdlog-1.2.1 basic_logger_mt moved to <spdlog/sinks/basic_file_sink.h>